services:
    jhg.extra.twig.return_url_extension:
        class: Jhg\ExtraBundle\Twig\ReturnUrlExtension
        arguments: ["@jhg.extra.return_url_helper"]
        public: false
        tags:
            - { name: twig.extension }

    jhg.extra.twig.money_extension:
        class: Jhg\ExtraBundle\Twig\MoneyExtension
        arguments: ["@translator"]
        public: false
        tags:
            - { name: twig.extension }

    jhg.extra.twig.percentage_extension:
        class: Jhg\ExtraBundle\Twig\PercentageExtension
        arguments: ["@translator"]
        public: false
        tags:
            - { name: twig.extension }

    jhg.extra.twig.lipsum_extension:
        class: Jhg\ExtraBundle\Twig\LipsumExtension
        arguments: ["@translator"]
        public: false
        tags:
            - { name: twig.extension }